apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: maven-web-deployment 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template: 
    metadata: 
      labels:
        app: web 
    spec: 
      containers:
        - name: web-app-example 
          image: muralisocial123/cart-page-example:1.0
          ports: 
            - containerPort: 3000
